In [1]:
# Manual normalization
def norm_manual(data):
    n_max = max(data)
    n_min = min(data)
    l_data = len(data) # panjang data

    for i in range(0, l_data):
        data[i] = (data[i] - n_min) / (n_max - n_nim)


    return data

In [15]:
nilai = [10, 13, 14, 12] 
nilai_norm = norm_manual(nilai)
nilai_norm

NameError: name 'n_nim' is not defined

In [16]:
import numpy as np
from sklearn.preprocessing import MinMaxScaler, StandardScaler


In [12]:
data = [
    [100, 0.0001],
    [8, 0.05],
    [50, 0.005]
    [88, 0.07],
    [4, 0.1]
]
data = np.asarray(data)
data.shape

scaler = MinMaxScaler()

scaled = scaler.fit_transform(data)
print(scaled)

array([[0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
def stand_manual(data):
    n_mean = np.mean(data)
    n_std = np.std(data)
    l_data = len(data)

    for i in range(0, l_data):
        data[i] = (data[i] - n_mean) / n_std

    return data

In [14]:
nilai = [10, 11, 12, 13, 14, 15, 18, 20]
nilai_std = stand_manual(nilai)
nilai_std

[-1.2816138016780185,
 -0.9709195467257716,
 -0.6602252917735247,
 -0.3495310368212778,
 -0.03883678186903087,
 0.27185747308321606,
 1.2039402379399569,
 1.8253287478444506]

In [19]:
from numpy import asarray
from sklearn.preprocessing import StandardScaler

#define data
data = ([[100, 0.0001],
        [8, 0.05],
        [50, 0.0005],
        [88, 0.07],
        [4, 0.1]])

print ("Data asli:")
print(data)

#define standard scaler
scaler = StandardScaler()

print ("Data transform hasil standardisasi:")

#transform data
scaled = scaler.fit_transform(data)
print(scaled)

Data asli:
[[100, 0.0001], [8, 0.05], [50, 0.0005], [88, 0.07], [4, 0.1]]
Data transform hasil standardisasi:
[[ 1.26398112 -1.12411649]
 [-1.06174414  0.15015459]
 [ 0.         -1.1139019 ]
 [ 0.96062565  0.66088448]
 [-1.16286263  1.42697932]]


In [18]:
from sklearn.preprocessing import OrdinalEncoder

oe = OrdinalEncoder()

poly = [
    ['POLIEMA'],
    ['PENS'],
    ['PNJ'],
    ['POLBAN'],
    ['POLJIE']
]

poly_enc = oe.fit_transform(poly)
poly_enc

array([[3.],
       [0.],
       [1.],
       [2.],
       [4.]])

In [21]:
from sklearn.preprocessing import OneHotEncoder

oh = OneHotEncoder()

poly = [
    ['POLIEMA'],
    ['PENS'],
    ['PNJ'],
    ['POLBAN'],
    ['POLJIE']
]

poly_enc = oh.fit_transform(poly)
poly_enc.toarray()

array([[0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
from sklearn.feature_extraction import DictVectorizer

dv = DictVectorizer ()

dt = [
        {'name' : 'POLINEMA'},
        {'name' : 'PENS'},
        {'name' : 'PNJ'},
        {'name' : 'POLBAN'},
        {'name' : 'POLIJE'},
]

poly_dv = oh.fit_transform(poly)
poly_dv.toarray()

array([[0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.]])

In [29]:
#Corpus / Text
corpus = ['the house had a tiny little mouse',
    'the cat saw the mouse',
    'the mouse ran away from the house',
    'the cat finally ate the mouse',
    'the end of the mouse story']

In [30]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer(stop_words='english')

response = vectorizer.fit_transform(corpus)
print(response)



  (0, 7)	0.2808823162882302
  (0, 6)	0.5894630806320427
  (0, 11)	0.5894630806320427
  (0, 5)	0.47557510189256375
  (1, 9)	0.7297183669435993
  (1, 2)	0.5887321837696324
  (1, 7)	0.3477147117091919
  (2, 1)	0.5894630806320427
  (2, 8)	0.5894630806320427
  (2, 7)	0.2808823162882302
  (2, 5)	0.47557510189256375
  (3, 0)	0.5894630806320427
  (3, 4)	0.5894630806320427
  (3, 2)	0.47557510189256375
  (3, 7)	0.2808823162882302
  (4, 10)	0.6700917930430479
  (4, 3)	0.6700917930430479
  (4, 7)	0.3193023297639811
